on:
  push:
    paths:
      - 'couse-materials/**.Rmd'

name: Render course materials

jobs:
  render:
    name: Render Rmarkdown files
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2 # This is important to set for `git diff-tree` to work below
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, tidyverse, dsbox
        run: |
          install.packages("remotes")
          remotes::install_cran(c("rmarkdown", "tidyverse", "here"))
          remotes::install_github("rstudio-education/dsbox")
        shell: Rscript {0}
      - name: Install Missing Packages
        run: |
          missing = checklist::missing_pkgs(dir = here::here("course-materials/"))
          if (length(missing) > 0)
            install.packages(pkgs = missing)
        shell: Rscript {0}
      - name: Render Rmarkdown files
        run: |
          RMD_PATH=($(git diff-tree --no-commit-id --name-only -r HEAD | grep '^course-materials/.*\\.[rR]md$'))
          Rscript -e 'for (file in commandArgs(TRUE)) rmarkdown::render(file)' ${RMD_PATH[*]}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
